### ISSUE TITLE
Update submodule

### ISSUE THREAD

**Issue by mapgccv** [NEOS-Server/Kestrel-AMPL-Windows#1]
Hi there, 
the submodule Kestrel-AMPL-Linux has been updated with support of the current policy server-side. The submodule reference in this repository should be updated to point to HEAD.
I can create a pull request, if needed, but it is such a trivial correction that it's probably not worth it.

**Comment by badgerben** [comment]
Updated. https://github.com/NEOS-Server/Kestrel-AMPL-Windows/commit/49572d4ecd812d879af639cd34dd005b71d2cdf9
